/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DayUI: typeof import('./src/components/EasyCron/tabs/DayUI.vue')['default']
    EasyCronInner: typeof import('./src/components/EasyCron/EasyCronInner.vue')['default']
    EasyCronInput: typeof import('./src/components/EasyCron/EasyCronInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HourUI: typeof import('./src/components/EasyCron/tabs/HourUI.vue')['default']
    MinuteUI: typeof import('./src/components/EasyCron/tabs/MinuteUI.vue')['default']
    MonthUI: typeof import('./src/components/EasyCron/tabs/MonthUI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondUI: typeof import('./src/components/EasyCron/tabs/SecondUI.vue')['default']
    WeekUI: typeof import('./src/components/EasyCron/tabs/WeekUI.vue')['default']
    YearUI: typeof import('./src/components/EasyCron/tabs/YearUI.vue')['default']
  }
}
